export const GETPRODUCT = {
  GET_PRODUCT: "GET_PRODUCT",
  GET_PRODUCT_FULFILLED: "GET_PRODUCT_FULFILLED",
  GET_PRODUCT_PENDING: "GET_PRODUCT_PENDING",
  GET_PRODUCT_REJECTED: "GET_PRODUCT_REJECTED",
};
