export const SIGNUP = {
  HANDLE_USERNAME: "HANDLE_USERNAME",
  HANDLE_EMAIL: "HANDLE_EMAIL",
  HANDLE_PASSWORD: "HANDLE_PASSWORD",

  POST_USER: "POST_USER",
  POST_USER_FULFILLED: "POST_USER_FULFILLED",
  POST_USER_PENDING: "POST_USER_PENDING",
  POST_USER_REJECTED: "POST_USER_REJECTED",
};
